### PR TITLE
Fix multiple field delimiter

### PR DESCRIPTION
**Pull request by gregordonsky**
fix Multiple Field Delimiter as specified in configuration

### CODE REVIEW

**Comment by wagnert** [comment]
@gregordonsky HI Gregor, i'll check it tomorrow and come back to you, if if've any questions, else i'll merge it, thanks again :)

**Review by wagnert — CHANGES_REQUESTED** [review]
@gregordonsky I think your solution won't work, because if the field value returned by `getValue()` is empty, the `$this->explode()` method wont return an empty array which is need for the following foreach structure.
 
The solution should more look like the following code

```php
$attributeOptionValues = $this->getValue(ColumnKeys::ATTRIBUTE_OPTION_VALUES, array(), function($value) { return $this->explode($value, $this->getMultipleFieldDelimiter()); });
```
as at least an empty array will be returned if the field value is empty. What do you think?

BTW, the `$attributeOptionSwatch` should also be fixed as it also will not return an empty array which can lead to warnings :-(

Would you please update your PR, thank you @gregordonsky :-)

**Comment by gregordonsky** [comment]
Your solution is right.
Meanwhile i update `$attributeOptionSwatch` too.

The attached File is a csv test with character `^` as multiple field delimiter and character `|` for multiple value delimiter.
It works if you have an attribute set called `Fato` and an attribute group name called `Features` already defined in your Magento.

Thank you @wagnert 
[attribute-import_test_2019-03-27_01.zip](https://github.com/techdivision/import-attribute/files/3013875/attribute-import_test_2019-03-27_01.zip)

**Review by wagnert — APPROVED** [review]

**Comment by wagnert** [comment]
@gregordonsky Perfect, thanks for contributing. We appreciated that very much!!! 👍

**Pull request merged**
